#!/bin/bash

if [ $(bluetoothctl show | grep "Powered: yes" -c) -eq 1 ]; then

  CONECTADOS=0

  for (( i = 1; i <= $(bluetoothctl devices | wc | awk '{print $1}'); i++ )); do
    echo $i
    if [[ $(bluetoothctl info $(bluetoothctl devices | awk -v i="$i" 'FNR == i {print $2}') | grep "Connected: yes" -c) -eq 1 ]]; then
      #DISPOSITIVO=$i
      ((CONECTADOS++))
    fi
  done

  if [[ $CONECTADOS -eq 0 ]]; then
    bluetoothctl power off
    notify-send "Desligando bluetooth"
  else
    echo "Dispositivo Conectado"
  fi

else
  echo "Bluetooth desligado"
fi
